name: Build YAnalyzers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [debug, release]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.402
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build YAnalyzers.slnf --configuration ${{ matrix.configuration }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.configuration }}
